[project]
name="file_cleaner"
version="0.1.0"
readme="README.md"
requires-python = ">=3.8"

[project.scripts]
file-cleaner="cleaner.cleaner:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cleaner"]